/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.universidad.forms;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author mateo
 */

public class Main extends JFrame{
    
    public Main() {
        initComponents();
        MainPnl pnlFondo = new MainPnl();
        this.add(pnlFondo, BorderLayout.CENTER);
        this.pack();
    }
    
    private void initComponents() {

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("Universidad Quipux");
        setLocationRelativeTo(this);
        setSize(1087, 643);
        setResizable(false);

        pack();
    }
    
    
    public static void main(String args[]) {
        new Main().setVisible(true);
    }
}

class MainPnl extends JPanel {

    /**
     * Creates new form Main
     */
    public MainPnl() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g){
        Dimension tamanio = getSize();        
        ImageIcon imagenFondo = new ImageIcon(getClass().getResource("/co/com/universidad/images/frmMainA.png"));
        g.drawImage(imagenFondo.getImage(), 0, 0, tamanio.width, tamanio.height, null);
        setOpaque(false);
        
        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEstudiantes = new javax.swing.JButton();
        btnProfesores = new javax.swing.JButton();
        btnMaterias = new javax.swing.JButton();
        btnNotas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/com/universidad/images/btnEstudiantes.png"))); // NOI18N
        btnEstudiantes.setBorder(null);
        btnEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantesActionPerformed(evt);
            }
        });

        btnProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/com/universidad/images/btnProfesores.png"))); // NOI18N
        btnProfesores.setBorder(null);

        btnMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/com/universidad/images/btnMaterias.png"))); // NOI18N
        btnMaterias.setBorder(null);

        btnNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/com/universidad/images/btnNotas.png"))); // NOI18N
        btnNotas.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstudiantesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstudiantes;
    private javax.swing.JButton btnMaterias;
    private javax.swing.JButton btnNotas;
    private javax.swing.JButton btnProfesores;
    // End of variables declaration//GEN-END:variables
}
